### ISSUE TITLE
Can stackless python support the tensorflow?

### ISSUE THREAD

**Issue by Marsxia** [stackless-dev/stackless#172]
i have installed the stackless python 3.6 and pip install tensorflow==1.10, but when i "import tensorflow" is error

**Comment by akruis** [comment]
@Marsxia First of all, please make sure, that you can install and use tensorflow with regular C-Python 3.6. I just failed to do so on my Windows laptop using 64bit C-Python 3.6.4. `pip install tensorflow==1.10` completed successfully, but `python -c 'import tensorflow'` failed to load _pywrap_tensorflow_internal

```
>>> import tensorflow
Traceback (most recent call last):
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\kruis_E\Pythons\3.6.4-64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\kruis_E\Pythons\3.6.4-64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\kruis_E\Pythons\3.6.4-64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\kruis_E\Pythons\3.6.4-64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\kruis_E\Pythons\3.6.4-64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>
```
My CPU lacks AVX instructions, which might be the cause of this failure.

Once you are able to install and use tensorflow with regular C-Python repeat the same installation using Stackless Python. If it fails, please provide detailed information about your setup (OS, installed software, CPU type, python version, output of `pip list`) and the complete error message. Only then I can try to reproduce the failure.

**Comment by akruis** [comment]
Just another data point: I just tried tensorflow 1.5 on my old Win7 laptop using v3.6.4-slp (64bit). It works, if I pin protobuf to version 3.5.1. Probably Stackless triggers protobuf bug [2974](https://github.com/protocolbuffers/protobuf/issues/2974).

**Comment by akruis** [comment]
Meanwhile protobuf 3.7.1 has been released and protobuf bug [2974](https://github.com/protocolbuffers/protobuf/issues/2974) is no longer a show stopper. But there is another protobuf incompatibility: protobuf bug [6094](https://github.com/protocolbuffers/protobuf/issues/6094).
If you use one of the workarounds described there, then Stackless supports tensorflow.
