### ISSUE TITLE
master-slp, OverflowError

### ISSUE THREAD

**Issue by akruis** [stackless-dev/stackless#174]
Stackless branch master-slp commit id 6e1250a3fdb4a
Visual Studio 2015, Debug x64

The following test case fails.
```
$ ./amd64/python_d.exe ../Stackless/unittests/test_thread.py -v BindThreadTest.test_bind_to_bogus_tid
test_bind_to_bogus_tid (__main__.BindThreadTest) ... ERROR

======================================================================
ERROR: test_bind_to_bogus_tid (__main__.BindThreadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../Stackless/unittests/test_thread.py", line 547, in test_bind_to_bogus_tid
    self.assertRaises(ValueError, t.bind_thread, sys.maxsize)
  File "E:\fg2\stackl35\stackless37\lib\unittest\case.py", line 743, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "E:\fg2\stackl35\stackless37\lib\unittest\case.py", line 178, in handle
    callable_obj(*args, **kwargs)
OverflowError: Python int too large to convert to C unsigned long
```
No failure for win32 or for Stackless 3.6.6

**Comment by akruis** [comment]
Fixed
